---

- hosts: all
  become: true
  tasks:
  
  - name: Install Apache2,php package, update apt
    package:
      name:
        - "{{ apache }}"
        - "{{ php }}"
      state: latest
      update_cache: yes

- hosts: rocky
  become: true
  tasks: 

  - name: permit traffic in default zone for https service
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled

